### ISSUE TITLE
List of items made of material X only checks first material of the items

### ISSUE THREAD

**Issue by Nandorianen** [Sheco/cdda-itembrowser#8] opened 2015-11-08 06:38 UTC
Items that are made of multiple materials only show in the list of items made of the first one.
For example, "headgear" is made of plastic and leather, shows up in "plastic" list, but not in "leather" list.

**Comment by Sheco** [comment] 2015-11-10 16:15
If I recall correctly that was by design, when cutting items you only get the primary material (right?), so I thought it would be safe to assume you would only want to search by the primary material.

Do you believe it's useful to include items if their secondary material matches?

**Comment by Nandorianen** [comment] 2015-11-10 18:15
It was the case, yes. It was changed some time ago, though, and at least in experimental builds you now get equal amounts of both materials. So cutting 10-volume pair of boots made of plastic and kevlar will net you up to 5 of both plastic chunks and kevlar plates.

Since there are relatively few item types you can safely cut up for rare materials like kevlar and nomex without worrying that they may be useful later, I'd say that being able to find all relevant items would be a useful thing.

**Comment by Sheco** [comment] 2015-11-11 17:01
This patch fixes the material catalog, now we only need to fix the item view, so it shows the correct material yields when cutting.

Items with 10 volume of 1 material still yield 10 of that material, right?

**Comment by Nandorianen** [comment] 2015-11-11 18:31
As far as I can tell, max salvage amount is volume / number of materials for each material, so yes.

**Comment by Sheco** [comment] 2015-11-11 23:16
Ok, that's fixed now, when viewing an item, it shows it can be cut into its secondary material.

I checked the game's  code and there's a salvage_multipler variable, which looks like is not used now, but I guess it will be used later, I'm not currently using it.

**Closed as completed** 2016-02-12 03:13 UTC
